### ISSUE TITLE
឵

### ISSUE THREAD

**Issue by ghost** [littlepriceonu/Pls-Donate-Self-Bot#3]

**Comment by littlepriceonu** [comment]
Trigon executor isn't supported (apparently lmao), the only true and tested executors are KRNL, Script-ware, and Synapse X.
And since I cannot find the documentation for Trigon, I cannot fix this error, sadly.
If you know the documentation for Trigon let me know and I'll try to fix this.

**Comment by RayBTA** [comment]
but apart from the server hop, it works very well, so I will continue using it without the server hop system, thanks

**Comment by RayBTA** [comment]
I would like to take advantage of the open topic to make a suggestion, what about making a rainbow color system with customizable color changeover time?

**Comment by littlepriceonu** [comment]
what do you mean by color system? What would the system be changing?
Sorry, I haven't been doing alot of roblox stuff recently and the Self Bot V2 is mostly on the back burner

**Comment by RayBTA** [comment]
a system that keeps changing the colors of the letters constantly, so that it was more eye-catching, just like this one, but in this case I used a separate script that is incompatible with yours, since both are constantly changing the text of the plate for its initial effects, so they end up not working, so I believe it would be interesting for you to integrate this into yours

(example)
![RobloxPlayerBeta_bnvekHxo8K](https://user-images.githubusercontent.com/97849414/206887094-8277127f-0bca-49a0-accf-815db7d2badc.gif)

**Comment by littlepriceonu** [comment]
maybe, that would be cool and probably something that wouldn't be to hard to add, but like I said mostly the pls donate bot and V2 are sorta on my "ill do it one of these days" list

**Comment by RayBTA** [comment]
yes, you did, but now there's something else to add to your "i'll do that someday" notebooks

**Comment by littlepriceonu** [comment]
fair lmao, thanks for the suggestion anyway, I'll make sure to add this in V2.
