### ISSUE TITLE
i cant seem to find out how to turn it on

### ISSUE THREAD

**Issue by D1v1N3L0v3RS** [littlepriceonu/Pls-Donate-Self-Bot#8]
basicly, i dont know anything about coding, but i seemed to make a decent starter bot, the only issue about this is i cant find out how to turn it on, Thanks for the consideration

**Comment by D1v1N3L0v3RS** [comment]
if anyone can help me id be thrilled to find out how

**Comment by littlepriceonu** [comment]
Roblox exploiting is in a really though spot right now, especially with Roblox's new anti-cheat Byfron. The way you used to run unauthorized code on Roblox is through an executor like Synapse X or Scriptware. Both of these options are no longer viable since all major executors are down to find a way to bypass Byfron, the best option right now is to roll back your version of Roblox to an older version of the Microsoft Store version of Roblox and use an executor like Fluxus or Electron. ALSO this script is very very very outdated, so most features might not work. And development on V2 is delayed because of reasons stated in this comment.
